### ISSUE TITLE
关于修改程式码

### ISSUE THREAD

**Issue by hakanaku1234** [blackcater/blog#5]
请问这个项目
如果想嵌入 react component 应该在哪修改呢

例如 类似这个语法应该要安插在哪个file才会生效呢~
```js
import Component from 'my-react-package'
<Component/>
```

**Comment by blackcater** [comment]
你是指在 `markdown` 里引入自定义的 React 组件么？

如果是这个意思的话，该项目并不支持，因为项目使用的是 `gatsby-transformer-remark` 而不是使用 `gatsby-plgin-mdx` 处理 `markdown`。

这个项目基本是归档状态（我自己也没用了😂）。

现在 `gatsby` 已经升级到 `v3.0` 了。这个项目设计的不是很好，也没用到 `gatsby` 许多高级特性，灵活性也不高，因此这项目可能我不会再去变动了。

我正在忙[另一个项目(unisite)](https://github.com/blackcater-labs/unisite)，他是支持 `gatsby-plugin-mdx` 的。
